apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: test
  replicas: 2
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test-container
          image: sqs-suscriber:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: AWS_KEY
              valueFrom:
                configMapKeyRef:
                  name: test-cfg
                  key: key
            - name: AWS_SECRET
              valueFrom:
                configMapKeyRef:
                  name: test-cfg
                  key: secret
