apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-suscriber
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: pubsub-suscriber
          image: us-central1-docker.pkg.dev/tareas-303400/general/pubsub-suscriber:1.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "128Mi"
              cpu: "250m"